_target_: src.models.diffusion_module.DiffusionModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.diffusion_model.DiffusionModel
  in_size: 32
  t_range: 1000
  img_depth: 1

# compile model for faster training with pytorch 2.0
compile: false
